name: Ruby Gem

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
